prep LunrCoreLmdb for NuGet
bleroy/lunr-core pull request #29
Opened 2021-01-09 22:52 UTC by danielcrenna

This is a PR for https://github.com/bleroy/lunr-core/issues/28.

It prepares `LunrCoreLmdb` to be a NuGet package.

If you can push it out the same way you're pushing out `LunrCore`, that would be great.

For now I can use the offline package for testing & development.

2021-01-10 19:26 UTC, bleroy requested changes

2021-01-10 19:26 UTC, bleroy commented on LunrCoreLmdb/LunrCoreLmdb.csproj
> +    <Description>A .NET Core, LMDB-backed port of Oliver Nightingale's lunr.js library, a lightweight full-text indexing library that is "a bit like Solr, but much smaller and not as bright." Icon ad
Let's put you as the main author for this package and remove Decent Consulting. Let's change the description to something like "LMDB storage add-on for LunrCore [...]". Also add yourself to the copyright.

2021-04-14 23:14 UTC, danielcrenna commented
I will make these changes but I'm going to hold off until my mutable index feature is completed and tested, which should be done this week.

2021-05-22 00:57 UTC, NimaAra commented
@danielcrenna Any update on the mutable index feature please?

2021-06-02 22:16 UTC, bleroy commented on LunrCoreLmdb/LunrCoreLmdb.csproj
> +    <Authors>Bertrand Le Roy</Authors>
```suggestion
    <Authors>Daniel Crenna, Bertrand Le Roy</Authors>
```

2021-06-02 22:19 UTC, bleroy commented
I'll merge that for now, for the sake of having a package on NuGet, which is long overdue. Let's take the mutable index changes when they're done, separately.

2021-06-02 22:24 UTC, bleroy approved these changes

2021-06-02 22:24 UTC, merged